
services:
  app:
    build: .
    container_name: timeless-aura-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./public/uploads:/usr/src/app/public/uploads
    restart: unless-stopped
